# - name: Decrypt large secret
#   run: ./.github/scripts/decrypt_secret.sh
#   env:
#     LARGE_FILE_PASSPHRASE: ${{ secrets.LARGE_FILE_PASSPHRASE }}

name: 'Upload to Google Drive'
inputs:
  file_id:  # id of input
    required: true
  filename:
    required: true
    # default: 'hello_world'
  my_secret:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
    - ${{ inputs.file_id }}
    - ${{ inputs.my_secret }}