name: 'Upload to Google Drive'
inputs:
  file_id:  # id of input on Google Drive
    required: true
  filename:
    required: true
  key_file:
    required: true
runs:
  using: 'docker'
  image: 'docker://ssinad/google-drive-update:latest'
  entrypoint: ["sh", "-c", "$(cat entrypoint.sh)"]
  args:
    - ${{ inputs.key_file }}
    - ${{ inputs.file_id }}
    - ${{ inputs.filename }}