name: 'Upload to Google Drive'
inputs:
  file_id:  # id of input on Google Drive
    required: true
  filename:
    required: true
  key_file:
    required: true
runs:
  using: 'docker'
  image: 'ssinad/google-drive-update-image:3.9.0-slim-buster'
  entrypoint: 'entrypoint.sh'
  args:
    - ${{ inputs.key_file }}
    - ${{ inputs.file_id }}
    - ${{ inputs.filename }}