name: 'Upload to Google Drive'
inputs:
  file_id:  # id of input on Google Drive
    required: true
  filename:
    required: true
  key_file:
    required: true
runs:
  using: 'docker'
  image: 'docker://ssinad/google-drive-update:1c7d71dbf6128db2d50c6bc5f5290c7dd47e3364'
  args:
    - ${{ inputs.key_file }}
    - ${{ inputs.file_id }}
    - ${{ inputs.filename }}