name: 'Upload to Google Drive'
inputs:
  file_id:  # id of input on Google Drive
    required: true
  filename:
    required: true
  key_file:
    required: true
runs:
  using: 'docker'
  image: 'docker://ssinad/google-drive-update:bff13ab2c9c1a0a7357063fdf8a658b8b20544c2'
  args:
    - ${{ inputs.key_file }}
    - ${{ inputs.file_id }}
    - ${{ inputs.filename }}