name: 'Upload to Google Drive'
inputs:
  file_id:  # id of input on Google Drive
    required: true
  filename:
    required: true
  key_file:
    required: true
runs:
  using: 'docker'
  image: 'docker://ssinad/google-drive-update:330842376fb7dbb68db7ba9dee506b02254d2d26'
  args:
    - ${{ inputs.key_file }}
    - ${{ inputs.file_id }}
    - ${{ inputs.filename }}